// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeuhltewbclcmnrlgfiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpldWhsdGV3YmNsY21ucmxnZml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDYyMDQsImV4cCI6MjA3MzI4MjIwNH0.13FIMF1GxkeoP56lqWPFUXa5zlPTFTRPNK6qGt6Vh88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});